//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_default p__default;
        
        private static SteamVR_Input_ActionSet_platformer p_platformer;
        
        private static SteamVR_Input_ActionSet_buggy p_buggy;
        
        private static SteamVR_Input_ActionSet_mixedreality p_mixedreality;
        
        private static SteamVR_Input_ActionSet_maze p_maze;
        
        private static SteamVR_Input_ActionSet_LookLetter p_LookLetter;
        
        private static SteamVR_Input_ActionSet_HoldHandle p_HoldHandle;
        
        public static SteamVR_Input_ActionSet_default _default
        {
            get
            {
                return SteamVR_Actions.p__default.GetCopy<SteamVR_Input_ActionSet_default>();
            }
        }
        
        public static SteamVR_Input_ActionSet_platformer platformer
        {
            get
            {
                return SteamVR_Actions.p_platformer.GetCopy<SteamVR_Input_ActionSet_platformer>();
            }
        }
        
        public static SteamVR_Input_ActionSet_buggy buggy
        {
            get
            {
                return SteamVR_Actions.p_buggy.GetCopy<SteamVR_Input_ActionSet_buggy>();
            }
        }
        
        public static SteamVR_Input_ActionSet_mixedreality mixedreality
        {
            get
            {
                return SteamVR_Actions.p_mixedreality.GetCopy<SteamVR_Input_ActionSet_mixedreality>();
            }
        }
        
        public static SteamVR_Input_ActionSet_maze maze
        {
            get
            {
                return SteamVR_Actions.p_maze.GetCopy<SteamVR_Input_ActionSet_maze>();
            }
        }
        
        public static SteamVR_Input_ActionSet_LookLetter LookLetter
        {
            get
            {
                return SteamVR_Actions.p_LookLetter.GetCopy<SteamVR_Input_ActionSet_LookLetter>();
            }
        }
        
        public static SteamVR_Input_ActionSet_HoldHandle HoldHandle
        {
            get
            {
                return SteamVR_Actions.p_HoldHandle.GetCopy<SteamVR_Input_ActionSet_HoldHandle>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p__default = ((SteamVR_Input_ActionSet_default)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_default>("/actions/default")));
            SteamVR_Actions.p_platformer = ((SteamVR_Input_ActionSet_platformer)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_platformer>("/actions/platformer")));
            SteamVR_Actions.p_buggy = ((SteamVR_Input_ActionSet_buggy)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_buggy>("/actions/buggy")));
            SteamVR_Actions.p_mixedreality = ((SteamVR_Input_ActionSet_mixedreality)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_mixedreality>("/actions/mixedreality")));
            SteamVR_Actions.p_maze = ((SteamVR_Input_ActionSet_maze)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_maze>("/actions/maze")));
            SteamVR_Actions.p_LookLetter = ((SteamVR_Input_ActionSet_LookLetter)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_LookLetter>("/actions/LookLetter")));
            SteamVR_Actions.p_HoldHandle = ((SteamVR_Input_ActionSet_HoldHandle)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_HoldHandle>("/actions/HoldHandle")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions._default,
                    SteamVR_Actions.platformer,
                    SteamVR_Actions.buggy,
                    SteamVR_Actions.mixedreality,
                    SteamVR_Actions.maze,
                    SteamVR_Actions.LookLetter,
                    SteamVR_Actions.HoldHandle};
        }
    }
}
